title: Graham's Data Science Portfolio
logo: /images/gitprofile.png
description: Business analyst and storyteller. Currently finishing my masters in business analytics from the University of Warwick in Coventry, England.
theme: jekyll-theme-minimal

