title: Graham's Data Science Portfolio
logo: /images/gitprofile.png
description: Email: GrahamChalfant@gmail.com \n LinkedIn: https://www.linkedin.com/in/grahamchalfant97/
theme: jekyll-theme-minimal

