title: Graham's Data Science Portfolio
logo: /images/gitprofile.png
description: Business analyst and storyteller. Currently finishing my masters in business analytics from the Universtiy of Warwick in Coventry, Engalnd.  
theme: jekyll-theme-minimal

